# Generated by Django 3.2 on 2021-09-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210928_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150, unique=True, verbose_name='Пароль'),
        ),
    ]
