# Generated by Django 3.2 on 2021-12-05 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridientamount',
            name='ingridient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingridient_amount', to='api.ingridient', verbose_name='Ингридиент'),
        ),
        migrations.AlterField(
            model_name='ingridientamount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_list', to='api.recipe', verbose_name='Рецепт'),
        ),
    ]
