# Generated by Django 3.2 on 2021-12-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211205_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridientamount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_amount', to='api.recipe', verbose_name='Рецепт'),
        ),
    ]
