# Generated by Django 3.2 on 2021-12-05 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ingridientamount_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridientamount',
            name='ingridient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingridient', verbose_name='Ингридиент'),
        ),
        migrations.AlterField(
            model_name='ingridientamount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recipe', verbose_name='Рецепт'),
        ),
    ]
