# Generated by Django 4.0.1 on 2022-02-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow_check_self_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
